# Generated by Django 5.1.7 on 2025-03-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
